spring:
  application:
    name: todolist

  datasource:
    url: jdbc:postgresql://localhost:5432/todolist_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true